### PR TITLE
Failing test in attribute

### PR DESCRIPTION
**Pull request by soukicz**
This problem is similar to #48. It is also possilbe that fix for #48 created this bug.

First line is working fine (with space in _class_) and second is failing.

### CODE REVIEW

**Comment by soukicz** [comment]
I have added one more commit by mistake - but it's just cosmetic stuff.

**Comment by goetas** [comment]
I see, will check soon

**Comment by goetas** [comment]
fixed with https://github.com/goetas/twital/issues/52

**Comment by soukicz** [comment]
Awesome! Thank you!

I am currently migrating project with ~10000 templates from 0.1.8 to 1.0.2. It seems that this was the last problem.

**Comment by goetas** [comment]
happy to hear that was helpful :)

**Pull request closed without merging**
